#!/bin/bash

type=$1

if [ -z "${type}" ]
then
    echo "Error: Processor type is required"
    exit 1
fi

for env_var in $(cat .env | xargs)
do
    export $env_var
done

bash gradlew clean :og-processors:${type}:build :og-apps:sample-${type}:build > /dev/null 2>&1
java -jar og-apps/sample-${type}/build/libs/sample-${type}-1.0-SNAPSHOT.jar
