package com.github.yarbshk.optget.apps.smplast;

import com.github.yarbshk.optget.commons.GenerateSample;
import com.github.yarbshk.optget.commons.SampleBuilder;

import static com.github.yarbshk.optget.commons.ReflectionUtils.printObjectFields;

@GenerateSample
public class Application {

    public static void main(String[] args) {
        // It isn't runnable from Intellij IDEA because it needs a plugin
        // to successfully run a getter generated by Lombok
        try {
            printObjectFields(SampleBuilder.of(Application.class));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
