#!/usr/bin/env sh

type=$1

if [ -z "${type}" ]
then
    echo "Error: Processor type is required"
    exit 1
fi

for env_var in $(cat .env | xargs)
do
    export $env_var
done

sh gradlew :og-apps:sample-${type}:run
