package com.github.yarbshk.optget.apps.ast;

import static com.github.yarbshk.optget.commons.ReflectionUtils.listObjectFields;

public class Application {

    public static void main(String[] args) throws Exception {
        // It isn't runnable from Intellij IDEA because it needs a plugin
        // to successfully run a getter generated by Lombok
        TargetDTO targetDTO = new TargetDTO(new Object(), "Foo", false);
        listObjectFields(targetDTO);
    }
}
